<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Attribute;
use App\Models\ProductAttributeValue;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('Starting ProductSeeder...');

        $brands = [
            'samsung' => Brand::firstOrCreate(['slug' => 'samsung'], ['name' => 'Samsung', 'is_visible' => true]),
            'intel' => Brand::firstOrCreate(['slug' => 'intel'], ['name' => 'Intel', 'is_visible' => true]),
            'nvidia' => Brand::firstOrCreate(['slug' => 'nvidia'], ['name' => 'NVIDIA', 'is_visible' => true]),
            'gigabyte' => Brand::firstOrCreate(['slug' => 'gigabyte'], ['name' => 'Gigabyte', 'is_visible' => true]),
            'xiaomi' => Brand::firstOrCreate(['slug' => 'xiaomi'], ['name' => 'Xiaomi', 'is_visible' => true]),
            'acer' => Brand::firstOrCreate(['slug' => 'acer'], ['name' => 'Acer', 'is_visible' => true]),
            'kingston' => Brand::firstOrCreate(['slug' => 'kingston'], ['name' => 'Kingston', 'is_visible' => true]),
            'asusrog' => Brand::firstOrCreate(['slug' => 'asusrog'], ['name' => 'ASUS ROG', 'is_visible' => true]),
            'asus' => Brand::firstOrCreate(['slug' => 'asus'], ['name' => 'ASUS', 'is_visible' => true]),
            'steelseries' => Brand::firstOrCreate(['slug' => 'steelseries'], ['name' => 'SteelSeries', 'is_visible' => true]),
            'logitech' => Brand::firstOrCreate(['slug' => 'logitech'], ['name' => 'Logitech', 'is_visible' => true]),
            'msi' => Brand::firstOrCreate(['slug' => 'msi'], ['name' => 'MSI', 'is_visible' => true]),
            'lenovo' => Brand::firstOrCreate(['slug' => 'lenovo'], ['name' => 'Lenovo', 'is_visible' => true]),
            'apple' => Brand::firstOrCreate(['slug' => 'apple'], ['name' => 'Apple', 'is_visible' => true]),
            'amd' => Brand::firstOrCreate(['slug' => 'amd'], ['name' => 'AMD', 'is_visible' => true]),
            'corsair' => Brand::firstOrCreate(['slug' => 'corsair'], ['name' => 'Corsair', 'is_visible' => true]),
            'lg' => Brand::firstOrCreate(['slug' => 'lg'], ['name' => 'LG', 'is_visible' => true]),
            'hyperx' => Brand::firstOrCreate(['slug' => 'hyperx'], ['name' => 'HyperX', 'is_visible' => true]),
            'razer' => Brand::firstOrCreate(['slug' => 'razer'], ['name' => 'Razer', 'is_visible' => true]),
            'dell' => Brand::firstOrCreate(['slug' => 'dell'], ['name' => 'Dell', 'is_visible' => true]),
            'hp' => Brand::firstOrCreate(['slug' => 'hp'], ['name' => 'HP', 'is_visible' => true]),
            'sony' => Brand::firstOrCreate(['slug' => 'sony'], ['name' => 'Sony', 'is_visible' => true]),
            'google' => Brand::firstOrCreate(['slug' => 'google'], ['name' => 'Google', 'is_visible' => true]),
            'benq' => Brand::firstOrCreate(['slug' => 'benq'], ['name' => 'BenQ', 'is_visible' => true]),
            'crucial' => Brand::firstOrCreate(['slug' => 'crucial'], ['name' => 'Crucial', 'is_visible' => true]),
            'gskill' => Brand::firstOrCreate(['slug' => 'gskill'], ['name' => 'G.Skill', 'is_visible' => true]),
            'seagate' => Brand::firstOrCreate(['slug' => 'seagate'], ['name' => 'Seagate', 'is_visible' => true]),
        ];

        $rootCategories = [
            'laptops-and-other' => Category::updateOrCreate(['slug' => 'laptops-and-other'], ['name' => 'Ноутбуки и прочее', 'is_visible' => true, 'sort_order' => 10]),
            'pc-components' => Category::updateOrCreate(['slug' => 'pc-components'], ['name' => 'Комплектующие для ПК', 'is_visible' => true, 'sort_order' => 20]),
            'peripherals' => Category::updateOrCreate(['slug' => 'peripherals'], ['name' => 'Периферия', 'is_visible' => true, 'sort_order' => 30]),
            'smartphones-tablets' => Category::updateOrCreate(['slug' => 'smartphones-tablets'], ['name' => 'Смартфоны и планшеты', 'is_visible' => true, 'sort_order' => 40]),
            'monitors-tv' => Category::updateOrCreate(['slug' => 'monitors-tv'], ['name' => 'Мониторы и ТВ', 'is_visible' => true, 'sort_order' => 50]),
        ];

        $categories = [
            'laptops-notebooks' => Category::updateOrCreate(['slug' => 'laptops-notebooks'], ['name' => 'Ноутбуки', 'parent_id' => $rootCategories['laptops-and-other']->id, 'is_visible' => true, 'sort_order' => 1]),
            'ultrabooks' => Category::updateOrCreate(['slug' => 'ultrabooks'], ['name' => 'Ультрабуки', 'parent_id' => $rootCategories['laptops-and-other']->id, 'is_visible' => true, 'sort_order' => 2]),
            'gaming-laptops' => Category::updateOrCreate(['slug' => 'gaming-laptops'], ['name' => 'Игровые ноутбуки', 'parent_id' => $rootCategories['laptops-and-other']->id, 'is_visible' => true, 'sort_order' => 3]),
            'components-cpu' => Category::updateOrCreate(['slug' => 'components-cpu'], ['name' => 'Процессоры (CPU)', 'parent_id' => $rootCategories['pc-components']->id, 'is_visible' => true, 'sort_order' => 1]),
            'components-gpu' => Category::updateOrCreate(['slug' => 'components-gpu'], ['name' => 'Видеокарты (GPU)', 'parent_id' => $rootCategories['pc-components']->id, 'is_visible' => true, 'sort_order' => 2]),
            'components-ram' => Category::updateOrCreate(['slug' => 'components-ram'], ['name' => 'Оперативная память (RAM)', 'parent_id' => $rootCategories['pc-components']->id, 'is_visible' => true, 'sort_order' => 3]),
            'components-motherboards' => Category::updateOrCreate(['slug' => 'components-motherboards'], ['name' => 'Материнские платы', 'parent_id' => $rootCategories['pc-components']->id, 'is_visible' => true, 'sort_order' => 4]),
            'components-ssd' => Category::updateOrCreate(['slug' => 'components-ssd'], ['name' => 'SSD накопители', 'parent_id' => $rootCategories['pc-components']->id, 'is_visible' => true, 'sort_order' => 5]),
            'peripherals-keyboards' => Category::updateOrCreate(['slug' => 'peripherals-keyboards'], ['name' => 'Клавиатуры', 'parent_id' => $rootCategories['peripherals']->id, 'is_visible' => true, 'sort_order' => 1]),
            'peripherals-mice' => Category::updateOrCreate(['slug' => 'peripherals-mice'], ['name' => 'Мыши', 'parent_id' => $rootCategories['peripherals']->id, 'is_visible' => true, 'sort_order' => 2]),
            'peripherals-headsets' => Category::updateOrCreate(['slug' => 'peripherals-headsets'], ['name' => 'Наушники и гарнитуры', 'parent_id' => $rootCategories['peripherals']->id, 'is_visible' => true, 'sort_order' => 3]),
            'smartfony' => Category::updateOrCreate(['slug' => 'smartfony'], ['name' => 'Смартфоны', 'parent_id' => $rootCategories['smartphones-tablets']->id, 'is_visible' => true, 'sort_order' => 1]),
            'tablets' => Category::updateOrCreate(['slug' => 'tablets'], ['name' => 'Планшеты', 'parent_id' => $rootCategories['smartphones-tablets']->id, 'is_visible' => true, 'sort_order' => 2]),
            'monitory-dlya-pk' => Category::updateOrCreate(['slug' => 'monitory-dlya-pk'], ['name' => 'Мониторы для ПК', 'parent_id' => $rootCategories['monitors-tv']->id, 'is_visible' => true, 'sort_order' => 1]),
            'televizory' => Category::updateOrCreate(['slug' => 'televizory'], ['name' => 'Телевизоры', 'parent_id' => $rootCategories['monitors-tv']->id, 'is_visible' => true, 'sort_order' => 2]),
        ];

        $defaultProductAttributes = [
            'is_visible' => true,
            'is_featured' => false,
            'is_new' => false,
            'on_sale' => false,
            'price' => 100.00,
            'sale_price' => null,
            'quantity' => 10,
            'sku' => null,
            'barcode' => null,
            'brand_id' => null,
            'category_id' => null,
            'meta_title' => null,
            'meta_description' => null,
            'meta_keywords' => null,
        ];

        $productsDataArray = [
            // Laptops (12 + 4 = 16)
            ['name' => 'Apple MacBook Air 13" M2, 8GB, 256GB SSD, Space Gray', 'price' => 22999.00, 'quantity' => 10, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => $brands['apple']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/D3D3D3/000000?text=MacBook+Air+M2', 'images' => ['https://placehold.co/800x800/D3D3D3/000000?text=MacBook+Air+M2'], 'description' => 'Ультратонкий и легкий MacBook Air с мощным чипом M2.', 'attributes_map' => ['screen_size' => 13.6, 'resolution' => '2560x1664', 'matrix_type' => 'IPS', 'ram_size' => 8, 'ram_type' => 'Unified', 'cpu_series' => 'Apple M2', 'cpu_cores' => 8, 'gpu_model' => '8-core GPU', 'storage_type' => 'SSD', 'ssd_volume' => 256, 'os_type' => 'macOS', 'color' => 'Серый космос', 'warranty' => 12]],
            ['name' => 'ASUS ROG Strix SCAR 17, Ryzen 9, 32GB, 2TB SSD, RTX 4090', 'price' => 75990.00, 'quantity' => 3, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['asusrog']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/E4000F/FFFFFF?text=ROG+Strix+SCAR', 'images' => ['https://placehold.co/800x800/E4000F/FFFFFF?text=ROG+Strix+SCAR'], 'description' => 'Максимальная производительность для киберспорта.', 'attributes_map' => ['screen_size' => 17.3, 'resolution' => '2560x1440', 'matrix_type' => 'IPS', 'refresh_rate' => 240, 'ram_size' => 32, 'ram_type' => 'DDR5', 'cpu_series' => 'AMD Ryzen 9', 'cpu_cores' => 16, 'storage_type' => 'SSD', 'ssd_volume' => 2000, 'gpu_model' => 'GeForce RTX 4090', 'gpu_memory' => 16, 'os_type' => 'Windows 11', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Lenovo Legion 5 Pro, Intel i7, 16GB, 1TB SSD, RTX 3070Ti', 'price' => 35500.00, 'quantity' => 8, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['lenovo']->id, 'thumbnail_url' => 'https://placehold.co/600x600/4A4A4A/FFFFFF?text=Legion+5+Pro', 'images' => ['https://placehold.co/800x800/4A4A4A/FFFFFF?text=Legion+5+Pro'], 'description' => 'Сбалансированный игровой ноутбук с отличным экраном.', 'attributes_map' => ['screen_size' => 16.0, 'resolution' => '2560x1600', 'matrix_type' => 'IPS', 'refresh_rate' => 165, 'ram_size' => 16, 'ram_type' => 'DDR5', 'cpu_series' => 'Intel Core i7', 'cpu_cores' => 14, 'storage_type' => 'SSD', 'ssd_volume' => 1024, 'gpu_model' => 'GeForce RTX 3070 Ti', 'gpu_memory' => 8, 'os_type' => 'Без ОС', 'color' => 'Серый', 'warranty' => 12]],
            ['name' => 'MSI Katana 15 B12V, i7-12650H, 16GB, 512GB SSD, RTX 4060', 'price' => 28900.00, 'quantity' => 11, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/DA291C/FFFFFF?text=MSI+Katana+15', 'images' => ['https://placehold.co/800x800/DA291C/FFFFFF?text=MSI+Katana+15'], 'description' => 'Современный игровой ноутбук с видеокартой RTX 40-й серии.', 'attributes_map' => ['screen_size' => 15.6, 'resolution' => '1920x1080', 'matrix_type' => 'IPS', 'refresh_rate' => 144, 'ram_size' => 16, 'ram_type' => 'DDR5', 'cpu_series' => 'Intel Core i7', 'cpu_cores' => 10, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => 'GeForce RTX 4060', 'gpu_memory' => 8, 'os_type' => 'Без ОС', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Acer Nitro 5 AN515, Ryzen 5, 16GB, 512GB SSD, RTX 3050Ti', 'price' => 21500.00, 'quantity' => 15, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['acer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF0000/FFFFFF?text=Acer+Nitro+5', 'images' => ['https://placehold.co/800x800/FF0000/FFFFFF?text=Acer+Nitro+5'], 'description' => 'Доступный игровой ноутбук для популярных онлайн-игр.', 'attributes_map' => ['screen_size' => 15.6, 'resolution' => '1920x1080', 'matrix_type' => 'IPS', 'refresh_rate' => 144, 'ram_size' => 16, 'ram_type' => 'DDR4', 'cpu_series' => 'AMD Ryzen 5', 'cpu_cores' => 6, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => 'GeForce RTX 3050 Ti', 'gpu_memory' => 4, 'os_type' => 'Без ОС', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Dell XPS 15 9530, i9-13900H, 32GB, 1TB SSD, RTX 4070', 'price' => 68000.00, 'quantity' => 5, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => $brands['dell']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/CCCCCC/000000?text=Dell+XPS+15', 'images' => ['https://placehold.co/800x800/CCCCCC/000000?text=Dell+XPS+15'], 'description' => 'Премиальный ультрабук для создателей контента с OLED-экраном.', 'attributes_map' => ['screen_size' => 15.6, 'resolution' => '3456x2160', 'matrix_type' => 'OLED', 'ram_size' => 32, 'ram_type' => 'DDR5', 'cpu_series' => 'Intel Core i9', 'cpu_cores' => 14, 'storage_type' => 'SSD', 'ssd_volume' => 1024, 'gpu_model' => 'GeForce RTX 4070', 'gpu_memory' => 8, 'os_type' => 'Windows 11 Pro', 'color' => 'Серебристый', 'warranty' => 24]],
            ['name' => 'HP Spectre x360 14, Core Ultra 7, 16GB, 1TB SSD', 'price' => 42000.00, 'quantity' => 7, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => $brands['hp']->id, 'thumbnail_url' => 'https://placehold.co/600x600/003F6A/FFFFFF?text=HP+Spectre+x360', 'images' => ['https://placehold.co/800x800/003F6A/FFFFFF?text=HP+Spectre+x360'], 'description' => 'Ноутбук-трансформер с сенсорным экраном и стилусом.', 'attributes_map' => ['screen_size' => 14.0, 'resolution' => '2880x1800', 'matrix_type' => 'OLED', 'ram_size' => 16, 'ram_type' => 'LPDDR5', 'cpu_series' => 'Intel Core Ultra 7', 'cpu_cores' => 16, 'storage_type' => 'SSD', 'ssd_volume' => 1024, 'gpu_model' => 'Intel Arc Graphics', 'os_type' => 'Windows 11', 'color' => 'Синий', 'warranty' => 12]],
            ['name' => 'Lenovo Yoga Slim 7, Ryzen 7, 16GB, 1TB SSD', 'price' => 25500.00, 'quantity' => 14, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => $brands['lenovo']->id, 'thumbnail_url' => 'https://placehold.co/600x600/50C878/FFFFFF?text=Yoga+Slim+7', 'images' => ['https://placehold.co/800x800/50C878/FFFFFF?text=Yoga+Slim+7'], 'description' => 'Тонкий и легкий ноутбук с длительным временем работы.', 'attributes_map' => ['screen_size' => 14.0, 'resolution' => '2880x1800', 'matrix_type' => 'OLED', 'refresh_rate' => 90, 'ram_size' => 16, 'ram_type' => 'LPDDR5', 'cpu_series' => 'AMD Ryzen 7', 'cpu_cores' => 8, 'storage_type' => 'SSD', 'ssd_volume' => 1024, 'gpu_model' => 'AMD Radeon Graphics', 'os_type' => 'Windows 11', 'color' => 'Бирюзовый', 'warranty' => 12]],
            ['name' => 'ASUS Zenbook 14 OLED, Core Ultra 5, 16GB, 512GB SSD', 'price' => 29800.00, 'quantity' => 9, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => $brands['asus']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/00529B/FFFFFF?text=Zenbook+14', 'images' => ['https://placehold.co/800x800/00529B/FFFFFF?text=Zenbook+14'], 'description' => 'Современный ультрабук с ярким OLED-дисплеем и процессором Meteor Lake.', 'attributes_map' => ['screen_size' => 14.0, 'resolution' => '1920x1200', 'matrix_type' => 'OLED', 'ram_size' => 16, 'ram_type' => 'LPDDR5X', 'cpu_series' => 'Intel Core Ultra 5', 'cpu_cores' => 12, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => 'Intel Arc Graphics', 'os_type' => 'Windows 11', 'color' => 'Темно-синий', 'warranty' => 24]],
            ['name' => 'Razer Blade 16, i9-14900HX, 32GB, 2TB SSD, RTX 4090', 'price' => 98000.00, 'quantity' => 2, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00FF00/000000?text=Razer+Blade+16', 'images' => ['https://placehold.co/800x800/00FF00/000000?text=Razer+Blade+16'], 'description' => 'Бескомпромиссный игровой ноутбук в стильном алюминиевом корпусе.', 'attributes_map' => ['screen_size' => 16.0, 'resolution' => '3840x2400', 'matrix_type' => 'Mini-LED', 'refresh_rate' => 120, 'ram_size' => 32, 'ram_type' => 'DDR5', 'cpu_series' => 'Intel Core i9', 'cpu_cores' => 24, 'storage_type' => 'SSD', 'ssd_volume' => 2048, 'gpu_model' => 'GeForce RTX 4090', 'gpu_memory' => 16, 'os_type' => 'Windows 11', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Acer Swift Go 14, Core Ultra 7, 16GB, 1TB SSD', 'price' => 27500.00, 'quantity' => 10, 'category_id' => $categories['laptops-notebooks']->id, 'brand_id' => $brands['acer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/87CEEB/000000?text=Acer+Swift+Go', 'images' => ['https://placehold.co/800x800/87CEEB/000000?text=Acer+Swift+Go'], 'description' => 'Универсальный ноутбук для работы и учебы с отличным экраном.', 'attributes_map' => ['screen_size' => 14.0, 'resolution' => '2880x1800', 'matrix_type' => 'OLED', 'ram_size' => 16, 'ram_type' => 'LPDDR5X', 'cpu_series' => 'Intel Core Ultra 7', 'cpu_cores' => 16, 'storage_type' => 'SSD', 'ssd_volume' => 1024, 'gpu_model' => 'Intel Arc Graphics', 'os_type' => 'Windows 11', 'color' => 'Серебристый', 'warranty' => 12]],
            ['name' => 'HP Pavilion 15, Ryzen 5, 8GB, 512GB SSD', 'price' => 15200.00, 'quantity' => 20, 'category_id' => $categories['laptops-notebooks']->id, 'brand_id' => $brands['hp']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FFD700/000000?text=HP+Pavilion+15', 'images' => ['https://placehold.co/800x800/FFD700/000000?text=HP+Pavilion+15'], 'description' => 'Надежный ноутбук для повседневных задач и мультимедиа.', 'attributes_map' => ['screen_size' => 15.6, 'resolution' => '1920x1080', 'matrix_type' => 'IPS', 'ram_size' => 8, 'ram_type' => 'DDR4', 'cpu_series' => 'AMD Ryzen 5', 'cpu_cores' => 6, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => 'AMD Radeon Graphics', 'os_type' => 'Windows 11', 'color' => 'Золотой', 'warranty' => 12]],
            ['name' => 'Microsoft Surface Laptop 5 13.5", i5, 8GB, 256GB SSD', 'price' => 24500.00, 'quantity' => 9, 'category_id' => $categories['ultrabooks']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'microsoft'], ['name' => 'Microsoft'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/7F7F7F/FFFFFF?text=Surface+Laptop+5', 'images' => ['https://placehold.co/800x800/7F7F7F/FFFFFF?text=Surface+Laptop+5'], 'description' => 'Элегантный и легкий ноутбук с сенсорным экраном PixelSense.', 'attributes_map' => ['screen_size' => 13.5, 'resolution' => '2256x1504', 'matrix_type' => 'PixelSense', 'ram_size' => 8, 'ram_type' => 'LPDDR5X', 'cpu_series' => 'Intel Core i5', 'cpu_cores' => 10, 'storage_type' => 'SSD', 'ssd_volume' => 256, 'gpu_model' => 'Intel Iris Xe', 'os_type' => 'Windows 11', 'color' => 'Платина', 'warranty' => 12]],
            ['name' => 'Gigabyte AORUS 17X, i9-13980HX, 32GB, 2TB SSD, RTX 4080', 'price' => 65000.00, 'quantity' => 4, 'category_id' => $categories['gaming-laptops']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=AORUS+17X', 'images' => ['https://placehold.co/800x800/FF6400/FFFFFF?text=AORUS+17X'], 'description' => 'Мощный игровой ноутбук с передовой системой охлаждения.', 'attributes_map' => ['screen_size' => 17.3, 'resolution' => '2560x1440', 'matrix_type' => 'IPS', 'refresh_rate' => 240, 'ram_size' => 32, 'ram_type' => 'DDR5', 'cpu_series' => 'Intel Core i9', 'cpu_cores' => 24, 'storage_type' => 'SSD', 'ssd_volume' => 2048, 'gpu_model' => 'GeForce RTX 4080', 'gpu_memory' => 12, 'os_type' => 'Windows 11', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Lenovo ThinkPad X1 Carbon Gen 11, i7, 16GB, 512GB SSD', 'price' => 41000.00, 'quantity' => 10, 'category_id' => $categories['laptops-notebooks']->id, 'brand_id' => $brands['lenovo']->id, 'thumbnail_url' => 'https://placehold.co/600x600/E52D27/FFFFFF?text=ThinkPad+X1', 'images' => ['https://placehold.co/800x800/E52D27/FFFFFF?text=ThinkPad+X1'], 'description' => 'Легендарный бизнес-ноутбук, легкий, прочный и надежный.', 'attributes_map' => ['screen_size' => 14.0, 'resolution' => '1920x1200', 'matrix_type' => 'IPS', 'ram_size' => 16, 'ram_type' => 'LPDDR5', 'cpu_series' => 'Intel Core i7', 'cpu_cores' => 12, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => 'Intel Iris Xe', 'os_type' => 'Windows 11 Pro', 'color' => 'Черный', 'warranty' => 36]],
            ['name' => 'Apple MacBook Pro 16" M3 Pro, 18GB, 512GB SSD, Silver', 'price' => 58000.00, 'quantity' => 7, 'category_id' => $categories['laptops-notebooks']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/E0E0E0/000000?text=MacBook+Pro+16', 'images' => ['https://placehold.co/800x800/E0E0E0/000000?text=MacBook+Pro+16'], 'description' => 'Профессиональный ноутбук для самых требовательных задач с лучшим дисплеем на рынке.', 'attributes_map' => ['screen_size' => 16.2, 'resolution' => '3456x2234', 'matrix_type' => 'Liquid Retina XDR', 'ram_size' => 18, 'ram_type' => 'Unified', 'cpu_series' => 'Apple M3 Pro', 'cpu_cores' => 12, 'storage_type' => 'SSD', 'ssd_volume' => 512, 'gpu_model' => '18-core GPU', 'os_type' => 'macOS', 'color' => 'Серебристый', 'warranty' => 12]],

            // Headsets (8 + 2 = 10)
            ['name' => 'SteelSeries Arctis Nova Pro Wireless', 'price' => 6800.00, 'quantity' => 10, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['steelseries']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/FF5A00/FFFFFF?text=Arctis+Nova+Pro', 'images' => ['https://placehold.co/800x800/FF5A00/FFFFFF?text=Arctis+Nova+Pro'], 'description' => 'Беспроводная гарнитура премиум-класса с активным шумоподавлением.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Выдвижной', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Logitech G PRO X Wireless LIGHTSPEED', 'price' => 3900.00, 'quantity' => 15, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['logitech']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00B8FC/000000?text=Logitech+G+Pro+X', 'images' => ['https://placehold.co/800x800/00B8FC/000000?text=Logitech+G+Pro+X'], 'description' => 'Профессиональная игровая гарнитура, разработанная совместно с киберспортсменами.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Razer BlackShark V2 Pro', 'price' => 3500.00, 'quantity' => 12, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00FF00/000000?text=BlackShark+V2+Pro', 'images' => ['https://placehold.co/800x800/00FF00/000000?text=BlackShark+V2+Pro'], 'description' => 'Легкая беспроводная гарнитура для соревновательных игр.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'HyperX Cloud III Wireless', 'price' => 3200.00, 'quantity' => 20, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['hyperx']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Cloud+III', 'images' => ['https://placehold.co/800x800/ED1C24/FFFFFF?text=Cloud+III'], 'description' => 'Новое поколение легендарной гарнитуры Cloud с улучшенным комфортом.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Черно-красный', 'warranty' => 24]],
            ['name' => 'Corsair HS80 RGB Wireless', 'price' => 2900.00, 'quantity' => 18, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['corsair']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F0F0F0/000000?text=Corsair+HS80', 'images' => ['https://placehold.co/800x800/F0F0F0/000000?text=Corsair+HS80'], 'description' => 'Комфортная беспроводная гарнитура с поддержкой Dolby Atmos.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Несъемный', 'color' => 'Белый', 'warranty' => 24]],
            ['name' => 'ASUS ROG Delta S Animate', 'price' => 4100.00, 'quantity' => 9, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['asusrog']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF0036/FFFFFF?text=ROG+Delta+S', 'images' => ['https://placehold.co/800x800/FF0036/FFFFFF?text=ROG+Delta+S'], 'description' => 'Проводная гарнитура с ЦАП ESS 9281 и анимируемыми дисплеями на чашках.', 'attributes_map' => ['connection_type' => 'Проводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Sony WH-1000XM5', 'price' => 7500.00, 'quantity' => 11, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['sony']->id, 'thumbnail_url' => 'https://placehold.co/600x600/C0C0C0/000000?text=Sony+XM5', 'images' => ['https://placehold.co/800x800/C0C0C0/000000?text=Sony+XM5'], 'description' => 'Лучшие в классе наушники с шумоподавлением для музыки и звонков.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Встроенный', 'color' => 'Серебристый', 'warranty' => 12]],
            ['name' => 'Apple AirPods Pro 2', 'price' => 4800.00, 'quantity' => 25, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F5F5F7/000000?text=AirPods+Pro+2', 'images' => ['https://placehold.co/800x800/F5F5F7/000000?text=AirPods+Pro+2'], 'description' => 'Компактные беспроводные наушники с превосходным шумоподавлением.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Внутриканальные', 'microphone_type' => 'Встроенный', 'color' => 'Белый', 'warranty' => 12]],
            ['name' => 'HyperX Cloud Alpha Wireless', 'price' => 3800.00, 'quantity' => 14, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['hyperx']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D32F2F/FFFFFF?text=Cloud+Alpha+W', 'images' => ['https://placehold.co/800x800/D32F2F/FFFFFF?text=Cloud+Alpha+W'], 'description' => 'Беспроводная игровая гарнитура с рекордным временем работы до 300 часов.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Logitech G733 LIGHTSPEED Wireless RGB', 'price' => 2900.00, 'quantity' => 19, 'category_id' => $categories['peripherals-headsets']->id, 'brand_id' => $brands['logitech']->id, 'thumbnail_url' => 'https://placehold.co/600x600/8A2BE2/FFFFFF?text=Logitech+G733', 'images' => ['https://placehold.co/800x800/8A2BE2/FFFFFF?text=Logitech+G733'], 'description' => 'Легкая и стильная беспроводная гарнитура с RGB-подсветкой, доступная в нескольких цветах.', 'attributes_map' => ['connection_type' => 'Беспроводное', 'headphone_type' => 'Полноразмерные', 'microphone_type' => 'Съемный', 'color' => 'Лиловый', 'warranty' => 24]],

            // Smartphones (8 + 2 = 10)
            ['name' => 'Samsung Galaxy S24 Ultra 12/512GB Titanium Gray', 'price' => 28900.00, 'quantity' => 20, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['samsung']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/808080/FFFFFF?text=S24+Ultra', 'images' => ['https://placehold.co/800x800/808080/FFFFFF?text=S24+Ultra'], 'description' => 'Флагманский смартфон с Galaxy AI, титановым корпусом и лучшей камерой.', 'attributes_map' => ['screen_size' => 6.8, 'resolution' => '3120x1440', 'matrix_type' => 'Dynamic AMOLED 2X', 'ram_size' => 12, 'cpu_series' => 'Snapdragon 8 Gen 3', 'ssd_volume' => 512, 'os_type' => 'Android', 'battery_capacity' => 5000, 'color' => 'Титановый Серый', 'warranty' => 12]],
            ['name' => 'Apple iPhone 15 Pro Max 256GB Natural Titanium', 'price' => 29500.00, 'quantity' => 18, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['apple']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/BEBDB8/000000?text=iPhone+15+Pro', 'images' => ['https://placehold.co/800x800/BEBDB8/000000?text=iPhone+15+Pro'], 'description' => 'Новый iPhone с титановым дизайном, чипом A17 Pro и портом USB-C.', 'attributes_map' => ['screen_size' => 6.7, 'resolution' => '2796x1290', 'matrix_type' => 'Super Retina XDR', 'ram_size' => 8, 'cpu_series' => 'A17 Pro', 'ssd_volume' => 256, 'os_type' => 'iOS', 'battery_capacity' => 4422, 'color' => 'Натуральный титан', 'warranty' => 12]],
            ['name' => 'Google Pixel 8 Pro 12/256GB Obsidian', 'price' => 21000.00, 'quantity' => 15, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['google']->id, 'thumbnail_url' => 'https://placehold.co/600x600/2D2D2D/FFFFFF?text=Pixel+8+Pro', 'images' => ['https://placehold.co/800x800/2D2D2D/FFFFFF?text=Pixel+8+Pro'], 'description' => 'Смартфон с лучшей камерой на базе искусственного интеллекта и чистым Android.', 'attributes_map' => ['screen_size' => 6.7, 'resolution' => '2992x1344', 'matrix_type' => 'OLED', 'ram_size' => 12, 'cpu_series' => 'Google Tensor G3', 'ssd_volume' => 256, 'os_type' => 'Android', 'battery_capacity' => 5050, 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Xiaomi 14 12/512GB Black', 'price' => 18500.00, 'quantity' => 22, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['xiaomi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1C1C1E/FFFFFF?text=Xiaomi+14', 'images' => ['https://placehold.co/800x800/1C1C1E/FFFFFF?text=Xiaomi+14'], 'description' => 'Компактный флагман с оптикой Leica и сверхбыстрой зарядкой.', 'attributes_map' => ['screen_size' => 6.36, 'resolution' => '2670x1200', 'matrix_type' => 'AMOLED', 'ram_size' => 12, 'cpu_series' => 'Snapdragon 8 Gen 3', 'ssd_volume' => 512, 'os_type' => 'Android', 'battery_capacity' => 4610, 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Samsung Galaxy A55 8/256GB Awesome Navy', 'price' => 8500.00, 'quantity' => 30, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/000080/FFFFFF?text=Galaxy+A55', 'images' => ['https://placehold.co/800x800/000080/FFFFFF?text=Galaxy+A55'], 'description' => 'Народный хит. Отличный экран, влагозащита и премиальные материалы.', 'attributes_map' => ['screen_size' => 6.6, 'resolution' => '2340x1080', 'matrix_type' => 'Super AMOLED', 'ram_size' => 8, 'cpu_series' => 'Exynos 1480', 'ssd_volume' => 256, 'os_type' => 'Android', 'battery_capacity' => 5000, 'color' => 'Темно-синий', 'warranty' => 12]],
            ['name' => 'ASUS ROG Phone 8 Pro 16/512GB', 'price' => 29000.00, 'quantity' => 7, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['asusrog']->id, 'thumbnail_url' => 'https://placehold.co/600x600/333333/FFFFFF?text=ROG+Phone+8', 'images' => ['https://placehold.co/800x800/333333/FFFFFF?text=ROG+Phone+8'], 'description' => 'Ультимативный игровой смартфон с мощнейшим железом и системой охлаждения.', 'attributes_map' => ['screen_size' => 6.78, 'resolution' => '2400x1080', 'matrix_type' => 'AMOLED', 'ram_size' => 16, 'cpu_series' => 'Snapdragon 8 Gen 3', 'ssd_volume' => 512, 'os_type' => 'Android', 'battery_capacity' => 5500, 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Apple iPhone 15 128GB Blue', 'price' => 19800.00, 'quantity' => 25, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ADD8E6/000000?text=iPhone+15', 'images' => ['https://placehold.co/800x800/ADD8E6/000000?text=iPhone+15'], 'description' => 'Базовый iPhone с Dynamic Island, отличной камерой и чипом A16 Bionic.', 'attributes_map' => ['screen_size' => 6.1, 'resolution' => '2556x1179', 'matrix_type' => 'Super Retina XDR', 'ram_size' => 6, 'cpu_series' => 'A16 Bionic', 'ssd_volume' => 128, 'os_type' => 'iOS', 'battery_capacity' => 3349, 'color' => 'Голубой', 'warranty' => 12]],
            ['name' => 'Xiaomi Redmi Note 13 Pro+ 5G 12/512GB Midnight Black', 'price' => 9200.00, 'quantity' => 28, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['xiaomi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/3B3B3B/FFFFFF?text=Redmi+Note+13+Pro', 'images' => ['https://placehold.co/800x800/3B3B3B/FFFFFF?text=Redmi+Note+13+Pro'], 'description' => 'Субфлагман с изогнутым экраном, камерой 200 Мп и быстрой зарядкой 120 Вт.', 'attributes_map' => ['screen_size' => 6.67, 'resolution' => '2712x1220', 'matrix_type' => 'AMOLED', 'ram_size' => 12, 'cpu_series' => 'MediaTek Dimensity 7200 Ultra', 'ssd_volume' => 512, 'os_type' => 'Android', 'battery_capacity' => 5000, 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Samsung Galaxy Z Fold 5 12/256GB Icy Blue', 'price' => 38000.00, 'quantity' => 10, 'category_id' => $categories['smartfony']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/B4D4E1/000000?text=Z+Fold+5', 'images' => ['https://placehold.co/800x800/B4D4E1/000000?text=Z+Fold+5'], 'description' => 'Складной смартфон-планшет для максимальной продуктивности.', 'attributes_map' => ['screen_size' => 7.6, 'resolution' => '2176x1812', 'matrix_type' => 'Dynamic AMOLED 2X', 'ram_size' => 12, 'cpu_series' => 'Snapdragon 8 Gen 2', 'ssd_volume' => 256, 'os_type' => 'Android', 'battery_capacity' => 4400, 'color' => 'Голубой', 'warranty' => 12]],
            ['name' => 'OnePlus 12 16/512GB Emerald Green', 'price' => 17900.00, 'quantity' => 15, 'category_id' => $categories['smartfony']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'oneplus'], ['name' => 'OnePlus'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/00A693/FFFFFF?text=OnePlus+12', 'images' => ['https://placehold.co/800x800/00A693/FFFFFF?text=OnePlus+12'], 'description' => 'Флагманский убийца с превосходной производительностью и камерой Hasselblad.', 'attributes_map' => ['screen_size' => 6.82, 'resolution' => '3168x1440', 'matrix_type' => 'AMOLED', 'ram_size' => 16, 'cpu_series' => 'Snapdragon 8 Gen 3', 'ssd_volume' => 512, 'os_type' => 'Android', 'battery_capacity' => 5400, 'color' => 'Изумрудный', 'warranty' => 12]],

            // Monitors (8 + 2 = 10)
            ['name' => 'LG UltraGear 27GP850-B, 27" QHD Nano IPS 165Hz', 'price' => 8990.00, 'quantity' => 15, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['lg']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/A50034/FFFFFF?text=LG+UltraGear', 'images' => ['https://placehold.co/800x800/A50034/FFFFFF?text=LG+UltraGear'], 'description' => 'Игровой монитор с Nano IPS матрицей и G-Sync Compatible.', 'attributes_map' => ['screen_size' => 27.0, 'resolution' => '2560x1440', 'matrix_type' => 'Nano IPS', 'refresh_rate' => 165, 'response_time' => 1, 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Samsung Odyssey G7 32" QHD 240Hz', 'price' => 13500.00, 'quantity' => 9, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00BFFF/000000?text=Odyssey+G7', 'images' => ['https://placehold.co/800x800/00BFFF/000000?text=Odyssey+G7'], 'description' => 'Изогнутый игровой монитор с высокой частотой обновления.', 'attributes_map' => ['screen_size' => 32.0, 'resolution' => '2560x1440', 'matrix_type' => 'VA', 'refresh_rate' => 240, 'response_time' => 1, 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Dell UltraSharp U2723QE 27" 4K IPS Black', 'price' => 15500.00, 'quantity' => 11, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['dell']->id, 'thumbnail_url' => 'https://placehold.co/600x600/007DB8/FFFFFF?text=Dell+UltraSharp', 'images' => ['https://placehold.co/800x800/007DB8/FFFFFF?text=Dell+UltraSharp'], 'description' => 'Профессиональный 4K монитор для работы с цветом.', 'attributes_map' => ['screen_size' => 27.0, 'resolution' => '3840x2160', 'matrix_type' => 'IPS Black', 'refresh_rate' => 60, 'response_time' => 5, 'color' => 'Серебристый', 'warranty' => 36]],
            ['name' => 'ASUS ProArt PA279CRV 27" 4K', 'price' => 14800.00, 'quantity' => 8, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['asus']->id, 'thumbnail_url' => 'https://placehold.co/600x600/383838/FFFFFF?text=ASUS+ProArt', 'images' => ['https://placehold.co/800x800/383838/FFFFFF?text=ASUS+ProArt'], 'description' => 'Монитор для дизайнеров и фотографов с заводской калибровкой.', 'attributes_map' => ['screen_size' => 27.0, 'resolution' => '3840x2160', 'matrix_type' => 'IPS', 'refresh_rate' => 60, 'response_time' => 5, 'color' => 'Черный', 'warranty' => 36]],
            ['name' => 'MSI MAG 274UPF 27" 4K 144Hz', 'price' => 12900.00, 'quantity' => 13, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/E53E3E/FFFFFF?text=MSI+MAG', 'images' => ['https://placehold.co/800x800/E53E3E/FFFFFF?text=MSI+MAG'], 'description' => 'Игровой 4K монитор с быстрой IPS-матрицей.', 'attributes_map' => ['screen_size' => 27.0, 'resolution' => '3840x2160', 'matrix_type' => 'Rapid IPS', 'refresh_rate' => 144, 'response_time' => 1, 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Xiaomi Mi Curved Gaming Monitor 34" WQHD 144Hz', 'price' => 7800.00, 'quantity' => 20, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['xiaomi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6900/FFFFFF?text=Xiaomi+Monitor', 'images' => ['https://placehold.co/800x800/FF6900/FFFFFF?text=Xiaomi+Monitor'], 'description' => 'Широкоформатный изогнутый монитор для полного погружения в игры.', 'attributes_map' => ['screen_size' => 34.0, 'resolution' => '3440x1440', 'matrix_type' => 'VA', 'refresh_rate' => 144, 'response_time' => 4, 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Gigabyte M32U 31.5" 4K 144Hz', 'price' => 16500.00, 'quantity' => 7, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=Gigabyte+M32U', 'images' => ['https://placehold.co/800x800/FF6400/FFFFFF?text=Gigabyte+M32U'], 'description' => 'Большой игровой 4K-монитор со встроенным KVM-переключателем.', 'attributes_map' => ['screen_size' => 31.5, 'resolution' => '3840x2160', 'matrix_type' => 'IPS', 'refresh_rate' => 144, 'response_time' => 1, 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'BenQ GW2480 23.8" FHD IPS', 'price' => 2800.00, 'quantity' => 25, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['benq']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EE3224/FFFFFF?text=BenQ+GW2480', 'images' => ['https://placehold.co/800x800/EE3224/FFFFFF?text=BenQ+GW2480'], 'description' => 'Надежный офисный монитор с технологией защиты зрения.', 'attributes_map' => ['screen_size' => 23.8, 'resolution' => '1920x1080', 'matrix_type' => 'IPS', 'refresh_rate' => 60, 'response_time' => 5, 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Samsung Odyssey OLED G9 49" Dual QHD 240Hz', 'price' => 35000.00, 'quantity' => 5, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['samsung']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/1428A0/FFFFFF?text=Odyssey+OLED+G9', 'images' => ['https://placehold.co/800x800/1428A0/FFFFFF?text=Odyssey+OLED+G9'], 'description' => 'Ультимативный сверхширокий игровой монитор с QD-OLED матрицей.', 'attributes_map' => ['screen_size' => 49.0, 'resolution' => '5120x1440', 'matrix_type' => 'QD-OLED', 'refresh_rate' => 240, 'response_time' => 0.03, 'color' => 'Серебристый', 'warranty' => 24]],
            ['name' => 'Acer Predator X34 V 34" OLED UWQHD 175Hz', 'price' => 25000.00, 'quantity' => 6, 'category_id' => $categories['monitory-dlya-pk']->id, 'brand_id' => $brands['acer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/151515/00A1DE?text=Predator+X34', 'images' => ['https://placehold.co/800x800/151515/00A1DE?text=Predator+X34'], 'description' => 'Изогнутый OLED монитор для полного погружения с глубоким черным цветом.', 'attributes_map' => ['screen_size' => 34.0, 'resolution' => '3440x1440', 'matrix_type' => 'OLED', 'refresh_rate' => 175, 'response_time' => 0.1, 'color' => 'Черный', 'warranty' => 24]],

            // TVs (8)
            ['name' => 'Samsung QE65QN90C 65" Neo QLED 4K', 'price' => 35000.00, 'quantity' => 8, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['samsung']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/0057B8/FFFFFF?text=Samsung+Neo+QLED', 'images' => ['https://placehold.co/800x800/0057B8/FFFFFF?text=Samsung+Neo+QLED'], 'description' => 'Яркий 4K телевизор с технологией Mini-LED и антибликовым покрытием.', 'attributes_map' => ['screen_size' => 65.0, 'resolution' => '3840x2160', 'matrix_type' => 'Neo QLED', 'refresh_rate' => 120, 'smart_tv_platform' => 'Tizen', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'LG OLED65C3 65" OLED evo 4K', 'price' => 42000.00, 'quantity' => 6, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['lg']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D9002D/FFFFFF?text=LG+OLED+C3', 'images' => ['https://placehold.co/800x800/D9002D/FFFFFF?text=LG+OLED+C3'], 'description' => 'Телевизор с идеальным черным цветом и высокой контрастностью.', 'attributes_map' => ['screen_size' => 65.0, 'resolution' => '3840x2160', 'matrix_type' => 'OLED', 'refresh_rate' => 120, 'smart_tv_platform' => 'webOS', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Sony XR-55A95L 55" QD-OLED 4K', 'price' => 55000.00, 'quantity' => 4, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['sony']->id, 'thumbnail_url' => 'https://placehold.co/600x600/303030/FFFFFF?text=Sony+QD-OLED', 'images' => ['https://placehold.co/800x800/303030/FFFFFF?text=Sony+QD-OLED'], 'description' => 'Телевизор премиум-класса с технологией QD-OLED для непревзойденного качества изображения.', 'attributes_map' => ['screen_size' => 55.0, 'resolution' => '3840x2160', 'matrix_type' => 'QD-OLED', 'refresh_rate' => 120, 'smart_tv_platform' => 'Google TV', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Xiaomi TV A2 55" 4K', 'price' => 9800.00, 'quantity' => 20, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['xiaomi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F56600/FFFFFF?text=Xiaomi+TV+A2', 'images' => ['https://placehold.co/800x800/F56600/FFFFFF?text=Xiaomi+TV+A2'], 'description' => 'Доступный 4K телевизор на Android TV с тонким металлическим корпусом.', 'attributes_map' => ['screen_size' => 55.0, 'resolution' => '3840x2160', 'matrix_type' => 'LED', 'refresh_rate' => 60, 'smart_tv_platform' => 'Android TV', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'LG 43UQ75006LG 43" LED 4K', 'price' => 7500.00, 'quantity' => 25, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['lg']->id, 'thumbnail_url' => 'https://placehold.co/600x600/A50034/FFFFFF?text=LG+43+UQ75', 'images' => ['https://placehold.co/800x800/A50034/FFFFFF?text=LG+43+UQ75'], 'description' => 'Компактный 4K телевизор для спальни или кухни с быстрым Smart TV.', 'attributes_map' => ['screen_size' => 43.0, 'resolution' => '3840x2160', 'matrix_type' => 'LED', 'refresh_rate' => 60, 'smart_tv_platform' => 'webOS', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Samsung The Frame QE50LS03B 50" QLED 4K', 'price' => 21000.00, 'quantity' => 10, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EAE7DC/000000?text=The+Frame', 'images' => ['https://placehold.co/800x800/EAE7DC/000000?text=The+Frame'], 'description' => 'Интерьерный телевизор, который в выключенном состоянии показывает картины.', 'attributes_map' => ['screen_size' => 50.0, 'resolution' => '3840x2160', 'matrix_type' => 'QLED', 'refresh_rate' => 60, 'smart_tv_platform' => 'Tizen', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Sony BRAVIA 9 75" Mini LED 4K', 'price' => 78000.00, 'quantity' => 3, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['sony']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/505050/FFFFFF?text=Sony+BRAVIA+9', 'images' => ['https://placehold.co/800x800/505050/FFFFFF?text=Sony+BRAVIA+9'], 'description' => 'Флагманский телевизор 2024 года с рекордной яркостью и контрастностью.', 'attributes_map' => ['screen_size' => 75.0, 'resolution' => '3840x2160', 'matrix_type' => 'Mini-LED', 'refresh_rate' => 120, 'smart_tv_platform' => 'Google TV', 'color' => 'Темно-серый', 'warranty' => 24]],
            ['name' => 'LG StanbyME 27"', 'price' => 18000.00, 'quantity' => 5, 'category_id' => $categories['televizory']->id, 'brand_id' => $brands['lg']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F0EAD6/000000?text=LG+StanbyME', 'images' => ['https://placehold.co/800x800/F0EAD6/000000?text=LG+StanbyME'], 'description' => 'Уникальный беспроводной телевизор на колесиках с сенсорным экраном.', 'attributes_map' => ['screen_size' => 27.0, 'resolution' => '1920x1080', 'matrix_type' => 'IPS', 'refresh_rate' => 60, 'smart_tv_platform' => 'webOS', 'color' => 'Белый', 'warranty' => 12]],

            // Tablets (8)
            ['name' => 'Apple iPad Pro 11" M4 256GB Wi-Fi Space Black', 'price' => 25000.00, 'quantity' => 12, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['apple']->id, 'is_new' => true, 'thumbnail_url' => 'https://placehold.co/600x600/1D1D1F/FFFFFF?text=iPad+Pro+M4', 'images' => ['https://placehold.co/800x800/1D1D1F/FFFFFF?text=iPad+Pro+M4'], 'description' => 'Невероятно тонкий и мощный планшет с революционным Tandem OLED экраном.', 'attributes_map' => ['screen_size' => 11.0, 'resolution' => '2420x1668', 'matrix_type' => 'OLED', 'cpu_series' => 'Apple M4', 'ssd_volume' => 256, 'os_type' => 'iPadOS', 'network_support' => 'Wi-Fi', 'color' => 'Черный космос', 'warranty' => 12]],
            ['name' => 'Samsung Galaxy Tab S9 Ultra 12/512GB Wi-Fi Graphite', 'price' => 26500.00, 'quantity' => 9, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/4A4A4A/FFFFFF?text=Tab+S9+Ultra', 'images' => ['https://placehold.co/800x800/4A4A4A/FFFFFF?text=Tab+S9+Ultra'], 'description' => 'Огромный и производительный планшет для работы и развлечений с защитой от воды.', 'attributes_map' => ['screen_size' => 14.6, 'resolution' => '2960x1848', 'matrix_type' => 'Dynamic AMOLED 2X', 'cpu_series' => 'Snapdragon 8 Gen 2', 'ssd_volume' => 512, 'os_type' => 'Android', 'network_support' => 'Wi-Fi', 'color' => 'Графит', 'warranty' => 12]],
            ['name' => 'Xiaomi Pad 6 8/256GB Gravity Gray', 'price' => 7800.00, 'quantity' => 25, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['xiaomi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/808080/FFFFFF?text=Xiaomi+Pad+6', 'images' => ['https://placehold.co/800x800/808080/FFFFFF?text=Xiaomi+Pad+6'], 'description' => 'Сбалансированный планшет с экраном 144 Гц и металлическим корпусом.', 'attributes_map' => ['screen_size' => 11.0, 'resolution' => '2880x1800', 'matrix_type' => 'IPS', 'cpu_series' => 'Snapdragon 870', 'ssd_volume' => 256, 'os_type' => 'Android', 'network_support' => 'Wi-Fi', 'color' => 'Серый', 'warranty' => 12]],
            ['name' => 'Lenovo Tab P12 8/128GB Storm Grey', 'price' => 8200.00, 'quantity' => 18, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['lenovo']->id, 'thumbnail_url' => 'https://placehold.co/600x600/778899/FFFFFF?text=Lenovo+Tab+P12', 'images' => ['https://placehold.co/800x800/778899/FFFFFF?text=Lenovo+Tab+P12'], 'description' => 'Планшет с большим 3K экраном и акустикой JBL для просмотра фильмов.', 'attributes_map' => ['screen_size' => 12.7, 'resolution' => '2944x1840', 'matrix_type' => 'IPS', 'cpu_series' => 'MediaTek Dimensity 7050', 'ssd_volume' => 128, 'os_type' => 'Android', 'network_support' => 'Wi-Fi', 'color' => 'Серый', 'warranty' => 12]],
            ['name' => 'Apple iPad Air 13" M2 128GB Wi-Fi Blue', 'price' => 18500.00, 'quantity' => 15, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/A0D6E8/000000?text=iPad+Air+M2', 'images' => ['https://placehold.co/800x800/A0D6E8/000000?text=iPad+Air+M2'], 'description' => 'Теперь с большим экраном 13 дюймов и мощью чипа M2.', 'attributes_map' => ['screen_size' => 13.0, 'resolution' => '2732x2048', 'matrix_type' => 'IPS', 'cpu_series' => 'Apple M2', 'ssd_volume' => 128, 'os_type' => 'iPadOS', 'network_support' => 'Wi-Fi', 'color' => 'Голубой', 'warranty' => 12]],
            ['name' => 'Samsung Galaxy Tab S9 FE+ 8/128GB Wi-Fi Mint', 'price' => 13500.00, 'quantity' => 20, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/98FF98/000000?text=Tab+S9+FE%2B', 'images' => ['https://placehold.co/800x800/98FF98/000000?text=Tab+S9+FE%2B'], 'description' => 'Доступная версия флагманского планшета с большим экраном и стилусом в комплекте.', 'attributes_map' => ['screen_size' => 12.4, 'resolution' => '2560x1600', 'matrix_type' => 'IPS', 'cpu_series' => 'Exynos 1380', 'ssd_volume' => 128, 'os_type' => 'Android', 'network_support' => 'Wi-Fi', 'color' => 'Мятный', 'warranty' => 12]],
            ['name' => 'Razer Edge Wi-Fi', 'price' => 9500.00, 'quantity' => 8, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/44D62C/000000?text=Razer+Edge', 'images' => ['https://placehold.co/800x800/44D62C/000000?text=Razer+Edge'], 'description' => 'Портативная игровая консоль на Android с AMOLED-экраном 144 Гц.', 'attributes_map' => ['screen_size' => 6.8, 'resolution' => '2400x1080', 'matrix_type' => 'AMOLED', 'cpu_series' => 'Snapdragon G3x Gen 1', 'ssd_volume' => 128, 'os_type' => 'Android', 'network_support' => 'Wi-Fi', 'color' => 'Черный', 'warranty' => 12]],
            ['name' => 'Apple iPad 10.9 10th Gen 64GB Wi-Fi Silver', 'price' => 9900.00, 'quantity' => 22, 'category_id' => $categories['tablets']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EAEAEA/000000?text=iPad+10th+Gen', 'images' => ['https://placehold.co/800x800/EAEAEA/000000?text=iPad+10th+Gen'], 'description' => 'Базовый iPad в современном дизайне с большим экраном и портом USB-C.', 'attributes_map' => ['screen_size' => 10.9, 'resolution' => '2360x1640', 'matrix_type' => 'IPS', 'cpu_series' => 'A14 Bionic', 'ssd_volume' => 64, 'os_type' => 'iPadOS', 'network_support' => 'Wi-Fi', 'color' => 'Серебристый', 'warranty' => 12]],

            // === START OF NEW PC COMPONENTS ===

            // CPUs (10)
            ['name' => 'Intel Core i9-14900K', 'price' => 15500.00, 'quantity' => 15, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['intel']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/0071C5/FFFFFF?text=i9-14900K', 'description' => 'Флагманский процессор Intel для максимальной производительности в играх и рабочих задачах.', 'attributes_map' => ['cpu_series' => 'Intel Core i9', 'socket' => 'LGA 1700', 'cpu_cores' => 24, 'cpu_threads' => 32, 'integrated_graphics' => 'Intel UHD 770', 'warranty' => 36]],
            ['name' => 'Intel Core i7-14700K', 'price' => 11200.00, 'quantity' => 25, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['intel']->id, 'thumbnail_url' => 'https://placehold.co/600x600/0071C5/FFFFFF?text=i7-14700K', 'description' => 'Высокопроизводительный процессор с оптимальным соотношением ядер и частоты.', 'attributes_map' => ['cpu_series' => 'Intel Core i7', 'socket' => 'LGA 1700', 'cpu_cores' => 20, 'cpu_threads' => 28, 'integrated_graphics' => 'Intel UHD 770', 'warranty' => 36]],
            ['name' => 'Intel Core i5-14600K', 'price' => 8500.00, 'quantity' => 40, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['intel']->id, 'thumbnail_url' => 'https://placehold.co/600x600/0071C5/FFFFFF?text=i5-14600K', 'description' => 'Лучший выбор для игровых сборок среднего и высокого класса.', 'attributes_map' => ['cpu_series' => 'Intel Core i5', 'socket' => 'LGA 1700', 'cpu_cores' => 14, 'cpu_threads' => 20, 'integrated_graphics' => 'Intel UHD 770', 'warranty' => 36]],
            ['name' => 'Intel Core i5-13400F', 'price' => 5400.00, 'quantity' => 50, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['intel']->id, 'thumbnail_url' => 'https://placehold.co/600x600/0071C5/FFFFFF?text=i5-13400F', 'description' => 'Народный процессор для доступных игровых ПК. Требует дискретную видеокарту.', 'attributes_map' => ['cpu_series' => 'Intel Core i5', 'socket' => 'LGA 1700', 'cpu_cores' => 10, 'cpu_threads' => 16, 'integrated_graphics' => 'Нет', 'warranty' => 36]],
            ['name' => 'AMD Ryzen 9 7950X3D', 'price' => 16800.00, 'quantity' => 12, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['amd']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Ryzen+9+7950X3D', 'description' => 'Ультимативный игровой процессор с технологией 3D V-Cache для непревзойденной производительности.', 'attributes_map' => ['cpu_series' => 'AMD Ryzen 9', 'socket' => 'AM5', 'cpu_cores' => 16, 'cpu_threads' => 32, 'integrated_graphics' => 'AMD Radeon Graphics', 'warranty' => 36]],
            ['name' => 'AMD Ryzen 7 7800X3D', 'price' => 10500.00, 'quantity' => 35, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['amd']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Ryzen+7+7800X3D', 'description' => 'Самый популярный процессор для игр благодаря огромному L3-кэшу.', 'attributes_map' => ['cpu_series' => 'AMD Ryzen 7', 'socket' => 'AM5', 'cpu_cores' => 8, 'cpu_threads' => 16, 'integrated_graphics' => 'AMD Radeon Graphics', 'warranty' => 36]],
            ['name' => 'AMD Ryzen 7 7700X', 'price' => 8200.00, 'quantity' => 30, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['amd']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Ryzen+7+7700X', 'description' => 'Мощный 8-ядерный процессор для игр и работы на платформе AM5.', 'attributes_map' => ['cpu_series' => 'AMD Ryzen 7', 'socket' => 'AM5', 'cpu_cores' => 8, 'cpu_threads' => 16, 'integrated_graphics' => 'AMD Radeon Graphics', 'warranty' => 24]],
            ['name' => 'AMD Ryzen 5 7600X', 'price' => 5900.00, 'quantity' => 45, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['amd']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Ryzen+5+7600X', 'description' => 'Отличный стартовый процессор для платформы AM5, идеален для игровых сборок.', 'attributes_map' => ['cpu_series' => 'AMD Ryzen 5', 'socket' => 'AM5', 'cpu_cores' => 6, 'cpu_threads' => 12, 'integrated_graphics' => 'AMD Radeon Graphics', 'warranty' => 24]],
            ['name' => 'AMD Ryzen 5 5600G', 'price' => 3500.00, 'quantity' => 60, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['amd']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Ryzen+5+5600G', 'description' => 'Процессор со встроенной графикой для бюджетных сборок без видеокарты.', 'attributes_map' => ['cpu_series' => 'AMD Ryzen 5', 'socket' => 'AM4', 'cpu_cores' => 6, 'cpu_threads' => 12, 'integrated_graphics' => 'Radeon Vega 7', 'warranty' => 12]],
            ['name' => 'Intel Core i3-12100F', 'price' => 2300.00, 'quantity' => 70, 'category_id' => $categories['components-cpu']->id, 'brand_id' => $brands['intel']->id, 'thumbnail_url' => 'https://placehold.co/600x600/0071C5/FFFFFF?text=i3-12100F', 'description' => 'Лучший бюджетный процессор для начальных игровых систем.', 'attributes_map' => ['cpu_series' => 'Intel Core i3', 'socket' => 'LGA 1700', 'cpu_cores' => 4, 'cpu_threads' => 8, 'integrated_graphics' => 'Нет', 'warranty' => 36]],

            // GPUs (10)
            ['name' => 'ASUS ROG Strix GeForce RTX 4090 OC 24GB', 'price' => 52000.00, 'quantity' => 5, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['asusrog']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/B20022/FFFFFF?text=RTX+4090+Strix', 'description' => 'Бескомпромиссная флагманская видеокарта для игр в 4K с максимальными настройками.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4090', 'gpu_memory' => 24, 'memory_type' => 'GDDR6X', 'bus_width' => 384, 'warranty' => 36]],
            ['name' => 'MSI GeForce RTX 4080 SUPER 16G GAMING X SLIM', 'price' => 34000.00, 'quantity' => 10, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF423A/FFFFFF?text=RTX+4080+Super', 'description' => 'Мощная видеокарта для 4K гейминга в более тонком исполнении.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4080 Super', 'gpu_memory' => 16, 'memory_type' => 'GDDR6X', 'bus_width' => 256, 'warranty' => 36]],
            ['name' => 'Gigabyte GeForce RTX 4070 Ti SUPER GAMING OC 16G', 'price' => 25500.00, 'quantity' => 20, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=RTX+4070Ti+Super', 'description' => 'Отличный выбор для игр в 1440p с высокой частотой кадров.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4070 Ti Super', 'gpu_memory' => 16, 'memory_type' => 'GDDR6X', 'bus_width' => 256, 'warranty' => 36]],
            ['name' => 'ASUS Dual GeForce RTX 4070 SUPER OC Edition 12GB', 'price' => 18500.00, 'quantity' => 25, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['asus']->id, 'thumbnail_url' => 'https://placehold.co/600x600/404040/FFFFFF?text=RTX+4070+Super', 'description' => 'Сбалансированная видеокарта для 1440p гейминга с трассировкой лучей.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4070 Super', 'gpu_memory' => 12, 'memory_type' => 'GDDR6X', 'bus_width' => 192, 'warranty' => 36]],
            ['name' => 'MSI GeForce RTX 4060 Ti VENTUS 2X BLACK 8G OC', 'price' => 12300.00, 'quantity' => 30, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/5A5A5A/FFFFFF?text=RTX+4060Ti', 'description' => 'Народная видеокарта для комфортной игры в 1080p с технологией DLSS 3.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4060 Ti', 'gpu_memory' => 8, 'memory_type' => 'GDDR6', 'bus_width' => 128, 'warranty' => 36]],
            ['name' => 'Gigabyte GeForce RTX 4060 GAMING OC 8G', 'price' => 9500.00, 'quantity' => 40, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=RTX+4060', 'description' => 'Энергоэффективная видеокарта для современных игр в разрешении 1080p.', 'attributes_map' => ['gpu_model' => 'GeForce RTX 4060', 'gpu_memory' => 8, 'memory_type' => 'GDDR6', 'bus_width' => 128, 'warranty' => 36]],
            ['name' => 'Sapphire PULSE AMD Radeon RX 7900 XTX 24GB', 'price' => 31000.00, 'quantity' => 8, 'category_id' => $categories['components-gpu']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'sapphire'], ['name' => 'Sapphire'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/003366/FFFFFF?text=RX+7900+XTX', 'description' => 'Флагманская видеокарта от AMD, отличный конкурент для RTX 4080.', 'attributes_map' => ['gpu_model' => 'Radeon RX 7900 XTX', 'gpu_memory' => 24, 'memory_type' => 'GDDR6', 'bus_width' => 384, 'warranty' => 24]],
            ['name' => 'PowerColor Hellhound AMD Radeon RX 7800 XT 16GB', 'price' => 15500.00, 'quantity' => 22, 'category_id' => $categories['components-gpu']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'powercolor'], ['name' => 'PowerColor'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/7D26CD/FFFFFF?text=RX+7800+XT', 'description' => 'Лучшее предложение по производительности на доллар для 1440p гейминга.', 'attributes_map' => ['gpu_model' => 'Radeon RX 7800 XT', 'gpu_memory' => 16, 'memory_type' => 'GDDR6', 'bus_width' => 256, 'warranty' => 24]],
            ['name' => 'ASRock Challenger OC AMD Radeon RX 7700 XT 12GB', 'price' => 13200.00, 'quantity' => 28, 'category_id' => $categories['components-gpu']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'asrock'], ['name' => 'ASRock'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/3C3C3C/FFFFFF?text=RX+7700+XT', 'description' => 'Производительная видеокарта для игр в 1080p и 1440p.', 'attributes_map' => ['gpu_model' => 'Radeon RX 7700 XT', 'gpu_memory' => 12, 'memory_type' => 'GDDR6', 'bus_width' => 192, 'warranty' => 24]],
            ['name' => 'ASUS Dual AMD Radeon RX 6600 8GB', 'price' => 6500.00, 'quantity' => 35, 'category_id' => $categories['components-gpu']->id, 'brand_id' => $brands['asus']->id, 'thumbnail_url' => 'https://placehold.co/600x600/404040/FFFFFF?text=RX+6600', 'description' => 'Доступная видеокарта для начинающих геймеров, отлично подходит для 1080p.', 'attributes_map' => ['gpu_model' => 'Radeon RX 6600', 'gpu_memory' => 8, 'memory_type' => 'GDDR6', 'bus_width' => 128, 'warranty' => 24]],

            // RAM (10)
            ['name' => 'Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz CL30', 'price' => 3200.00, 'quantity' => 40, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['corsair']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/1B1B1B/FFFFFF?text=Corsair+DDR5', 'description' => 'Высокоскоростная память DDR5 с RGB-подсветкой, идеальна для AMD Ryzen 7000.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 32, 'memory_speed' => 6000, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'G.Skill Trident Z5 Neo RGB 32GB (2x16GB) DDR5 6000MHz CL30', 'price' => 3400.00, 'quantity' => 35, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['gskill']->id, 'thumbnail_url' => 'https://placehold.co/600x600/3A3A3A/FFFFFF?text=G.Skill+DDR5', 'description' => 'Оптимизированная для AMD EXPO память с агрессивным дизайном и низкой латентностью.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 32, 'memory_speed' => 6000, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'Kingston FURY Beast 32GB (2x16GB) DDR5 5600MHz', 'price' => 2800.00, 'quantity' => 50, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['kingston']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D4122C/FFFFFF?text=Kingston+DDR5', 'description' => 'Надежная и быстрая память DDR5 от известного производителя.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 32, 'memory_speed' => 5600, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'Crucial Pro 32GB (2x16GB) DDR5 5600MHz', 'price' => 2700.00, 'quantity' => 45, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['crucial']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00A9E0/FFFFFF?text=Crucial+DDR5', 'description' => 'Качественная и доступная память DDR5 без излишеств.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 32, 'memory_speed' => 5600, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'Corsair Vengeance LPX 32GB (2x16GB) DDR4 3200MHz', 'price' => 1800.00, 'quantity' => 60, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['corsair']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1B1B1B/FFFFFF?text=Corsair+DDR4', 'description' => 'Популярная низкопрофильная память DDR4, совместима с большинством кулеров.', 'attributes_map' => ['ram_type' => 'DDR4', 'memory_capacity' => 32, 'memory_speed' => 3200, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'Kingston FURY Beast 16GB (2x8GB) DDR4 3600MHz', 'price' => 1100.00, 'quantity' => 70, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['kingston']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D4122C/FFFFFF?text=Kingston+DDR4', 'description' => 'Стандартный комплект памяти DDR4 для большинства игровых сборок на AM4 или LGA 1700.', 'attributes_map' => ['ram_type' => 'DDR4', 'memory_capacity' => 16, 'memory_speed' => 3600, 'module_count' => 2, 'color' => 'Черный', 'warranty' => 60]],
            ['name' => 'G.Skill Ripjaws V 16GB (2x8GB) DDR4 3200MHz', 'price' => 950.00, 'quantity' => 65, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['gskill']->id, 'thumbnail_url' => 'https://placehold.co/600x600/A80000/FFFFFF?text=G.Skill+DDR4', 'description' => 'Надежная и быстрая память DDR4 по отличной цене.', 'attributes_map' => ['ram_type' => 'DDR4', 'memory_capacity' => 16, 'memory_speed' => 3200, 'module_count' => 2, 'color' => 'Красный', 'warranty' => 60]],
            ['name' => 'G.Skill Trident Z5 RGB 64GB (2x32GB) DDR5 6400MHz', 'price' => 6500.00, 'quantity' => 15, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['gskill']->id, 'thumbnail_url' => 'https://placehold.co/600x600/C0C0C0/000000?text=G.Skill+64GB', 'description' => 'Комплект большого объема для рабочих станций и энтузиастов.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 64, 'memory_speed' => 6400, 'module_count' => 2, 'color' => 'Серебристый', 'warranty' => 60]],
            ['name' => 'Crucial Pro 16GB (2x8GB) DDR4 3200MHz', 'price' => 900.00, 'quantity' => 80, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['crucial']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00A9E0/FFFFFF?text=Crucial+DDR4', 'description' => 'Простой и надежный комплект DDR4 для офисных и домашних ПК.', 'attributes_map' => ['ram_type' => 'DDR4', 'memory_capacity' => 16, 'memory_speed' => 3200, 'module_count' => 2, 'color' => 'Зеленый', 'warranty' => 60]],
            ['name' => 'Corsair Dominator Platinum RGB 32GB (2x16GB) DDR5 7200MHz', 'price' => 4800.00, 'quantity' => 20, 'category_id' => $categories['components-ram']->id, 'brand_id' => $brands['corsair']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EFEFEF/000000?text=Dominator+DDR5', 'description' => 'Премиальная оперативная память с высокой частотой и яркой подсветкой Capellix.', 'attributes_map' => ['ram_type' => 'DDR5', 'memory_capacity' => 32, 'memory_speed' => 7200, 'module_count' => 2, 'color' => 'Белый', 'warranty' => 60]],

            // Motherboards (10)
            ['name' => 'ASUS ROG MAXIMUS Z790 HERO', 'price' => 17000.00, 'quantity' => 10, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['asusrog']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/202020/FFFFFF?text=Z790+HERO', 'description' => 'Флагманская материнская плата для процессоров Intel с широкими возможностями разгона и подключения.', 'attributes_map' => ['socket' => 'LGA 1700', 'chipset' => 'Intel Z790', 'form_factor' => 'ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 192, 'warranty' => 36]],
            ['name' => 'MSI MAG Z790 TOMAHAWK WIFI', 'price' => 8500.00, 'quantity' => 25, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/454545/FFFFFF?text=Z790+TOMAHAWK', 'description' => 'Популярная материнская плата Z790 с отличной системой питания и набором портов.', 'attributes_map' => ['socket' => 'LGA 1700', 'chipset' => 'Intel Z790', 'form_factor' => 'ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 192, 'warranty' => 36]],
            ['name' => 'Gigabyte B760M AORUS ELITE AX', 'price' => 5200.00, 'quantity' => 40, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=B760M+AORUS', 'description' => 'Отличная Micro-ATX плата для сборок на Intel без разгона, но с поддержкой быстрой DDR5 памяти.', 'attributes_map' => ['socket' => 'LGA 1700', 'chipset' => 'Intel B760', 'form_factor' => 'Micro-ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 192, 'warranty' => 36]],
            ['name' => 'ASUS TUF GAMING B760-PLUS WIFI D4', 'price' => 4800.00, 'quantity' => 35, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['asus']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FFC20E/000000?text=TUF+B760+D4', 'description' => 'Надежная материнская плата для процессоров Intel с поддержкой более доступной памяти DDR4.', 'attributes_map' => ['socket' => 'LGA 1700', 'chipset' => 'Intel B760', 'form_factor' => 'ATX', 'ram_type' => 'DDR4', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'ASUS ROG STRIX X670E-F GAMING WIFI', 'price' => 12500.00, 'quantity' => 15, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['asusrog']->id, 'thumbnail_url' => 'https://placehold.co/600x600/202020/FFFFFF?text=X670E-F+Strix', 'description' => 'Высокопроизводительная плата для процессоров AMD Ryzen 7000 с поддержкой PCIe 5.0.', 'attributes_map' => ['socket' => 'AM5', 'chipset' => 'AMD X670E', 'form_factor' => 'ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'Gigabyte B650 AORUS ELITE AX', 'price' => 6800.00, 'quantity' => 30, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=B650+AORUS', 'description' => 'Народный хит для платформы AM5, предлагает отличный баланс цены и возможностей.', 'attributes_map' => ['socket' => 'AM5', 'chipset' => 'AMD B650', 'form_factor' => 'ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'MSI MAG B650 TOMAHAWK WIFI', 'price' => 6500.00, 'quantity' => 32, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['msi']->id, 'thumbnail_url' => 'https://placehold.co/600x600/454545/FFFFFF?text=B650+TOMAHAWK', 'description' => 'Надежная и хорошо оснащенная материнская плата для процессоров AMD Ryzen.', 'attributes_map' => ['socket' => 'AM5', 'chipset' => 'AMD B650', 'form_factor' => 'ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'ASRock B650M PG Riptide WiFi', 'price' => 5100.00, 'quantity' => 40, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'asrock'], ['name' => 'ASRock'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/1E90FF/FFFFFF?text=B650M+Riptide', 'description' => 'Доступная Micro-ATX плата для компактных сборок на AM5.', 'attributes_map' => ['socket' => 'AM5', 'chipset' => 'AMD B650', 'form_factor' => 'Micro-ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'ASUS Prime B550M-A WIFI II', 'price' => 3200.00, 'quantity' => 50, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['asus']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F0F0F0/000000?text=B550M-A+Prime', 'description' => 'Надежная и доступная плата для процессоров AMD Ryzen 5000 серии на сокете AM4.', 'attributes_map' => ['socket' => 'AM4', 'chipset' => 'AMD B550', 'form_factor' => 'Micro-ATX', 'ram_type' => 'DDR4', 'max_ram_size' => 128, 'warranty' => 36]],
            ['name' => 'Gigabyte Z790 AORUS XTREME X', 'price' => 28000.00, 'quantity' => 5, 'category_id' => $categories['components-motherboards']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=Z790+XTREME+X', 'description' => 'Бескомпромиссная материнская плата E-ATX для энтузиастов и экстремального разгона.', 'attributes_map' => ['socket' => 'LGA 1700', 'chipset' => 'Intel Z790', 'form_factor' => 'E-ATX', 'ram_type' => 'DDR5', 'max_ram_size' => 192, 'warranty' => 36]],

            // SSDs (10)
            ['name' => 'Samsung 990 Pro 2TB NVMe M.2 SSD', 'price' => 4500.00, 'quantity' => 30, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['samsung']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/1428A0/FFFFFF?text=990+Pro+2TB', 'description' => 'Один из самых быстрых PCIe 4.0 SSD на рынке, идеален для игр и профессиональных задач.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 7450, 'write_speed' => 6900, 'warranty' => 60]],
            ['name' => 'Samsung 980 Pro 1TB NVMe M.2 SSD', 'price' => 2800.00, 'quantity' => 40, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1428A0/FFFFFF?text=980+Pro+1TB', 'description' => 'Высокопроизводительный PCIe 4.0 накопитель, отличный выбор для системного диска.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 1000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 7000, 'write_speed' => 5000, 'warranty' => 60]],
            ['name' => 'Crucial P5 Plus 2TB NVMe M.2 SSD', 'price' => 3800.00, 'quantity' => 35, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['crucial']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00A9E0/FFFFFF?text=P5+Plus+2TB', 'description' => 'Быстрый и надежный PCIe 4.0 SSD по конкурентной цене.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 6600, 'write_speed' => 5000, 'warranty' => 60]],
            ['name' => 'Kingston KC3000 1TB NVMe M.2 SSD', 'price' => 2600.00, 'quantity' => 45, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['kingston']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D4122C/FFFFFF?text=KC3000+1TB', 'description' => 'Накопитель с высокими скоростями чтения и записи, подходит для требовательных пользователей.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 1024, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 7000, 'write_speed' => 6000, 'warranty' => 60]],
            ['name' => 'WD Black SN850X 2TB NVMe M.2 SSD', 'price' => 4400.00, 'quantity' => 28, 'category_id' => $categories['components-ssd']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'wd'], ['name' => 'Western Digital'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/000000/FFFFFF?text=SN850X+2TB', 'description' => 'SSD игровой серии, оптимизированный для быстрой загрузки игр и уровней.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 7300, 'write_speed' => 6600, 'warranty' => 60]],
            ['name' => 'Seagate FireCuda 530 1TB NVMe M.2 SSD', 'price' => 2700.00, 'quantity' => 33, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['seagate']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F58220/FFFFFF?text=FireCuda+530', 'description' => 'Накопитель с высокой выносливостью (TBW), совместим с PlayStation 5.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 1000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 7300, 'write_speed' => 6000, 'warranty' => 60]],
            ['name' => 'Crucial MX500 1TB SATA III 2.5" SSD', 'price' => 1800.00, 'quantity' => 60, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['crucial']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00A9E0/FFFFFF?text=MX500+1TB', 'description' => 'Один из лучших SATA SSD, идеален для апгрейда старых ПК и ноутбуков.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 1000, 'form_factor' => '2.5"', 'interface' => 'SATA III', 'read_speed' => 560, 'write_speed' => 510, 'warranty' => 60]],
            ['name' => 'Samsung 870 EVO 2TB SATA III 2.5" SSD', 'price' => 3400.00, 'quantity' => 50, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['samsung']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1428A0/FFFFFF?text=870+EVO+2TB', 'description' => 'Надежный и производительный SATA SSD большого объема для хранения игр и файлов.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => '2.5"', 'interface' => 'SATA III', 'read_speed' => 560, 'write_speed' => 530, 'warranty' => 60]],
            ['name' => 'Kingston NV2 2TB NVMe M.2 SSD', 'price' => 2900.00, 'quantity' => 70, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['kingston']->id, 'thumbnail_url' => 'https://placehold.co/600x600/D4122C/FFFFFF?text=NV2+2TB', 'description' => 'Бюджетный PCIe 4.0 накопитель большого объема, отличное соотношение цены и производительности.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 4.0 x4', 'read_speed' => 3500, 'write_speed' => 2800, 'warranty' => 36]],
            ['name' => 'Gigabyte AORUS Gen5 10000 2TB NVMe M.2 SSD', 'price' => 7500.00, 'quantity' => 15, 'category_id' => $categories['components-ssd']->id, 'brand_id' => $brands['gigabyte']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF6400/FFFFFF?text=AORUS+Gen5', 'description' => 'Накопитель нового поколения PCIe 5.0 с экстремальными скоростями.', 'attributes_map' => ['storage_type' => 'SSD', 'ssd_volume' => 2000, 'form_factor' => 'M.2 2280', 'interface' => 'PCIe 5.0 x4', 'read_speed' => 10000, 'write_speed' => 9500, 'warranty' => 60]],

            // === START OF NEW PERIPHERALS ===

            // Keyboards (10)
            ['name' => 'Logitech MX Keys S Wireless Keyboard', 'price' => 2500.00, 'quantity' => 30, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['logitech']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/3D4346/FFFFFF?text=MX+Keys+S', 'description' => 'Премиальная офисная клавиатура с умной подсветкой и тихими клавишами.', 'attributes_map' => ['keyboard_type' => 'Мембранная', 'connection_type' => 'Беспроводное', 'layout' => 'Полноразмерная', 'backlight' => 'Белая', 'color' => 'Графит', 'warranty' => 24]],
            ['name' => 'Razer BlackWidow V4 Pro Mechanical Keyboard', 'price' => 4800.00, 'quantity' => 20, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00FF00/000000?text=BlackWidow+V4', 'description' => 'Флагманская механическая клавиатура с RGB-подсветкой, макро-клавишами и подставкой под запястья.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Проводное', 'switch_type' => 'Razer Green', 'layout' => 'Полноразмерная', 'backlight' => 'RGB', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'SteelSeries Apex Pro TKL (2023) Keyboard', 'price' => 4200.00, 'quantity' => 25, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['steelseries']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF5A00/FFFFFF?text=Apex+Pro+TKL', 'description' => 'Компактная клавиатура с регулируемыми переключателями OmniPoint 2.0.', 'attributes_map' => ['keyboard_type' => 'Механическая (магнитная)', 'connection_type' => 'Проводное', 'switch_type' => 'OmniPoint 2.0', 'layout' => 'TKL', 'backlight' => 'RGB', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Corsair K100 AIR Wireless Ultra-Thin Mechanical Keyboard', 'price' => 5500.00, 'quantity' => 15, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['corsair']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1B1B1B/FFFFFF?text=K100+AIR', 'description' => 'Ультратонкая беспроводная механическая клавиатура с переключателями Cherry MX ULP.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Беспроводное', 'switch_type' => 'Cherry MX ULP Tactile', 'layout' => 'Полноразмерная', 'backlight' => 'RGB', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'HyperX Alloy Origins Core Mechanical Keyboard', 'price' => 2100.00, 'quantity' => 35, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['hyperx']->id, 'thumbnail_url' => 'https://placehold.co/600x600/ED1C24/FFFFFF?text=Alloy+Origins+Core', 'description' => 'Компактная и надежная TKL-клавиатура в алюминиевом корпусе.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Проводное', 'switch_type' => 'HyperX Red', 'layout' => 'TKL', 'backlight' => 'RGB', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'ASUS ROG Azoth Wireless Mechanical Keyboard', 'price' => 5200.00, 'quantity' => 18, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['asusrog']->id, 'thumbnail_url' => 'https://placehold.co/600x600/B20022/FFFFFF?text=ROG+Azoth', 'description' => 'Премиальная беспроводная клавиатура формата 75% для энтузиастов с OLED-дисплеем.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Беспроводное', 'switch_type' => 'ROG NX Snow', 'layout' => '75%', 'backlight' => 'RGB', 'color' => 'Серый', 'warranty' => 24]],
            ['name' => 'Logitech G915 TKL LIGHTSPEED Wireless RGB Keyboard', 'price' => 4500.00, 'quantity' => 22, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['logitech']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00B8FC/000000?text=G915+TKL', 'description' => 'Низкопрофильная беспроводная механическая клавиатура для геймеров.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Беспроводное', 'switch_type' => 'GL Tactile', 'layout' => 'TKL', 'backlight' => 'RGB', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Apple Magic Keyboard', 'price' => 2200.00, 'quantity' => 28, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F5F5F7/000000?text=Magic+Keyboard', 'description' => 'Минималистичная и удобная беспроводная клавиатура для экосистемы Apple.', 'attributes_map' => ['keyboard_type' => 'Мембранная', 'connection_type' => 'Беспроводное', 'layout' => 'Компактная', 'backlight' => 'Нет', 'color' => 'Серебристый', 'warranty' => 12]],
            ['name' => 'Keychron K2 Pro Wireless Mechanical Keyboard', 'price' => 2800.00, 'quantity' => 26, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'keychron'], ['name' => 'Keychron'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/4D4D4D/FFFFFF?text=Keychron+K2+Pro', 'description' => 'Популярная беспроводная механическая клавиатура с поддержкой QMK/VIA.', 'attributes_map' => ['keyboard_type' => 'Механическая', 'connection_type' => 'Беспроводное', 'switch_type' => 'Gateron Brown', 'layout' => '75%', 'backlight' => 'Белая', 'color' => 'Серый', 'warranty' => 12]],
            ['name' => 'Microsoft Ergonomic Keyboard', 'price' => 1200.00, 'quantity' => 40, 'category_id' => $categories['peripherals-keyboards']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'microsoft'], ['name' => 'Microsoft'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/5E5E5E/FFFFFF?text=MS+Ergo+Keyboard', 'description' => 'Проводная эргономичная клавиатура для комфортной печати в течение всего дня.', 'attributes_map' => ['keyboard_type' => 'Мембранная', 'connection_type' => 'Проводное', 'layout' => 'Эргономичная', 'backlight' => 'Нет', 'color' => 'Черный', 'warranty' => 24]],

            // Mice (10)
            ['name' => 'Logitech MX Master 3S Wireless Mouse', 'price' => 2400.00, 'quantity' => 35, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['logitech']->id, 'is_featured' => true, 'thumbnail_url' => 'https://placehold.co/600x600/3D4346/FFFFFF?text=MX+Master+3S', 'description' => 'Лучшая беспроводная мышь для работы и продуктивности с тихими кликами.', 'attributes_map' => ['sensor_type' => 'Лазерный', 'connection_type' => 'Беспроводное', 'dpi' => 8000, 'button_count' => 7, 'ergonomics' => 'Для правшей', 'color' => 'Графит', 'warranty' => 24]],
            ['name' => 'Razer DeathAdder V3 Pro Wireless Gaming Mouse', 'price' => 2900.00, 'quantity' => 25, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/00FF00/000000?text=DeathAdder+V3', 'description' => 'Ультралегкая эргономичная беспроводная мышь для профессиональных геймеров.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 30000, 'button_count' => 5, 'ergonomics' => 'Для правшей', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Logitech G Pro X Superlight Wireless Gaming Mouse', 'price' => 2800.00, 'quantity' => 30, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['logitech']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1C1C1C/FFFFFF?text=G+Pro+Superlight', 'description' => 'Одна из самых популярных мышей в киберспорте, весит менее 63 грамм.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 25600, 'button_count' => 5, 'ergonomics' => 'Симметричная', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'SteelSeries Aerox 5 Wireless Gaming Mouse', 'price' => 2600.00, 'quantity' => 22, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['steelseries']->id, 'thumbnail_url' => 'https://placehold.co/600x600/FF5A00/FFFFFF?text=Aerox+5', 'description' => 'Легкая многожанровая беспроводная мышь с перфорированным корпусом и 9 программируемыми кнопками.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 18000, 'button_count' => 9, 'ergonomics' => 'Для правшей', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Razer Viper V2 Pro Wireless Gaming Mouse', 'price' => 2900.00, 'quantity' => 26, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EFEFEF/000000?text=Viper+V2+Pro', 'description' => 'Сверхлегкая (58 г) симметричная беспроводная мышь для соревновательных игр.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 30000, 'button_count' => 5, 'ergonomics' => 'Симметричная', 'color' => 'Белый', 'warranty' => 24]],
            ['name' => 'Corsair Scimitar RGB Elite MMO Gaming Mouse', 'price' => 1800.00, 'quantity' => 18, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['corsair']->id, 'thumbnail_url' => 'https://placehold.co/600x600/1B1B1B/FFC700?text=Scimitar+Elite', 'description' => 'Проводная мышь для MMO и MOBA игр с 12 программируемыми боковыми кнопками.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Проводное', 'dpi' => 18000, 'button_count' => 17, 'ergonomics' => 'Для правшей', 'color' => 'Черный', 'warranty' => 24]],
            ['name' => 'Logitech G502 X Plus LIGHTSPEED Wireless Gaming Mouse', 'price' => 3100.00, 'quantity' => 24, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['logitech']->id, 'thumbnail_url' => 'https://placehold.co/600x600/EFEFEF/000000?text=G502+X+Plus', 'description' => 'Новое поколение легендарной мыши G502 с оптико-механическими переключателями и RGB-подсветкой.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 25600, 'button_count' => 13, 'ergonomics' => 'Для правшей', 'color' => 'Белый', 'warranty' => 24]],
            ['name' => 'Apple Magic Mouse', 'price' => 1800.00, 'quantity' => 30, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['apple']->id, 'thumbnail_url' => 'https://placehold.co/600x600/F5F5F7/000000?text=Magic+Mouse', 'description' => 'Беспроводная мышь с Multi-Touch поверхностью для управления жестами в macOS.', 'attributes_map' => ['sensor_type' => 'Лазерный', 'connection_type' => 'Беспроводное', 'dpi' => 1300, 'button_count' => 2, 'ergonomics' => 'Симметричная', 'color' => 'Белый', 'warranty' => 12]],
            ['name' => 'Microsoft Bluetooth Ergonomic Mouse', 'price' => 1100.00, 'quantity' => 38, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => Brand::firstOrCreate(['slug' => 'microsoft'], ['name' => 'Microsoft'])->id, 'thumbnail_url' => 'https://placehold.co/600x600/B4D4E1/000000?text=MS+Ergo+Mouse', 'description' => 'Беспроводная эргономичная мышь для комфортной работы в течение дня.', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 2400, 'button_count' => 5, 'ergonomics' => 'Для правшей', 'color' => 'Пастельный синий', 'warranty' => 12]],
            ['name' => 'Razer Naga V2 Pro Wireless MMO Gaming Mouse', 'price' => 3800.00, 'quantity' => 15, 'category_id' => $categories['peripherals-mice']->id, 'brand_id' => $brands['razer']->id, 'thumbnail_url' => 'https://placehold.co/600x600/000000/00FF00?text=Naga+V2+Pro', 'description' => 'Универсальная беспроводная мышь со сменными боковыми панелями (2, 6 и 12 кнопок).', 'attributes_map' => ['sensor_type' => 'Оптический', 'connection_type' => 'Беспроводное', 'dpi' => 30000, 'button_count' => 20, 'ergonomics' => 'Для правшей', 'color' => 'Черный', 'warranty' => 24]],
        ];


        $allDbAttributes = Attribute::all()->keyBy('slug');

        foreach ($productsDataArray as $productData) {
            $productAttributesToSave = $productData['attributes_map'] ?? [];
            unset($productData['attributes_map']);

            if (isset($productData['images']) && is_array($productData['images'])) {
                $productData['images'] = json_encode($productData['images']);
            }
            $finalProductData = array_merge($defaultProductAttributes, $productData);

            if (empty($finalProductData['sku'])) $finalProductData['sku'] = Str::upper(Str::random(4) . '-' . Str::random(6));
            if (empty($finalProductData['meta_title'])) $finalProductData['meta_title'] = $finalProductData['name'] . ' - купить в Aura Computers';
            if (empty($finalProductData['meta_description'])) $finalProductData['meta_description'] = 'Купить ' . $finalProductData['name'] . '. ' . Str::limit(strip_tags($finalProductData['description'] ?? ''), 150);

            $slug = Str::slug($finalProductData['name'], '-');
            $originalSlug = $slug;
            $count = 1;
            while (Product::where('slug', $slug)->where('id', '!=', ($finalProductData['id'] ?? null))->exists()) {
                $slug = $originalSlug . '-' . $count++;
            }
            $finalProductData['slug'] = $slug;
            $createdProduct = Product::updateOrCreate(['slug' => $finalProductData['slug']], $finalProductData);

            if ($createdProduct && !empty($productAttributesToSave)) {
                foreach ($productAttributesToSave as $attributeSlug => $attributeValue) {

                    if (isset($allDbAttributes[$attributeSlug])) {
                        $dbAttribute = $allDbAttributes[$attributeSlug];

                        if ($attributeValue !== null && (is_string($attributeValue) ? trim($attributeValue) !== '' : true)) {
                            $pav = ProductAttributeValue::updateOrCreate(
                                ['product_id' => $createdProduct->id, 'attribute_id' => $dbAttribute->id],
                                []
                            );
                            $pav->setRelation('attributeDefinition', $dbAttribute);
                            $pav->value = $attributeValue;
                            $pav->save();
                        }
                    } else {
                        $this->command->warn("Attribute with slug '{$attributeSlug}' not found in DB for product '{$createdProduct->name}'. Ensure this attribute is defined in AttributeSeeder.");
                    }
                }
            }
        }
        $this->command->info('Product seeding completed.');
    }
}